# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7d00e71c7a64984e654b0acd7f7c0089f66d48459a6e0f2de100912e12d259083de1f7ab11f9bf9a9ec3eee0eb58fe741eb609318c1a71bb5cd9784a9a0f3b61

test:
  secret_key_base: a54395942e06976def6e21051e5d850b803d15f623cb10ae3f23632c538e4c7b199f10a9ff74a2b2a8a2d7e0bd37a662f6b795c19301f3a9606bf6665b185155

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
